// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_v1_codes_ts_code_ from "./routes/api/v1/codes/ts[code].ts";
import * as $contributing from "./routes/contributing.tsx";
import * as $edit_ts_code_ from "./routes/edit/ts[code].tsx";
import * as $index from "./routes/index.tsx";
import * as $integrating from "./routes/integrating.tsx";
import * as $og_ts_code_ from "./routes/og/ts[code].tsx";
import * as $propose from "./routes/propose.tsx";
import * as $tag_tag_ from "./routes/tag/[tag].tsx";
import * as $tag_index from "./routes/tag/index.tsx";
import * as $ts_code_ from "./routes/ts[code].tsx";
import * as $Editor from "./islands/Editor.tsx";
import * as $Search from "./islands/Search.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/v1/codes/ts[code].ts": $api_v1_codes_ts_code_,
    "./routes/contributing.tsx": $contributing,
    "./routes/edit/ts[code].tsx": $edit_ts_code_,
    "./routes/index.tsx": $index,
    "./routes/integrating.tsx": $integrating,
    "./routes/og/ts[code].tsx": $og_ts_code_,
    "./routes/propose.tsx": $propose,
    "./routes/tag/[tag].tsx": $tag_tag_,
    "./routes/tag/index.tsx": $tag_index,
    "./routes/ts[code].tsx": $ts_code_,
  },
  islands: {
    "./islands/Editor.tsx": $Editor,
    "./islands/Search.tsx": $Search,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
